library(rethinking)
library(dplyr)
library(bayesplot)

# diagnostic tools from Betancourt ####
util <- new.env()
source('~/Documents/classes/STANworkshop/material/1 - workflow/stan_utility.R', local=util)

# options for rstan #####
options(mc.cores=parallel::detectCores())
rstan_options(auto_write=TRUE)

# read in and format data #####
phenology_data <- read.csv("data/stan_input/phenology_heatsum.csv", stringsAsFactors = FALSE, header = TRUE)
#SPU_dat <- read.csv("~/Documents/research_phd/data/OrchardInfo/LodgepoleSPUs.csv", header=TRUE, stringsAsFactors = FALSE) %>%
#   dplyr::select(SPU_Name, Orchard)
SPU_dat <- read.csv("~/Documents/research_phd/data/OrchardInfo/LodgepoleSPUs.csv", header=TRUE, stringsAsFactors = FALSE) %>%
    dplyr::select(SPU_Name, Orchard)

phendf <- phenology_data %>%
    na.omit() %>%
    filter(daily_forcing_type=="ristos")#drop heatsums and keep ristos
phendf <- dplyr::left_join(phendf, SPU_dat)

#Create indexes that stan will like
#Create Clone IDs
phendf$CloneID <- group_indices(phendf, Clone)
#Create OrchardIDs
phendf$OrchardID <- group_indices(phendf, Orchard)
#Create ProvenanceIDs
phendf$ProvenanceID <- group_indices(phendf, SPU_Name)
#Create SiteIDs
phendf$SiteID <- group_indices(phendf, Site)
#Create SexIDs
phendf$SexID <- group_indices(phendf, Sex)
#Create TreeIDs
phendf$TreeID_new <- group_indices(phendf, TreeID)

phen <- phendf #make a copy that will let me translate between ids and values

#drop "non-numeric" cols to make stan quit complaining
phendf <- select(phendf, -Site, -SPU_Name, -Sex, -TreeID, -Phenophase, -Date, -Clone, -daily_forcing_type, -mean_temp, -daily_forcing, -DoY)

# run a version of the model in ulam, but not to fit ####

ulam_fit <- ulam(
    alist(
        #likelihood
        Phenophase_Derived ~ ordered_logistic(phi, cutpoints),
        #model
        phi <- beta[SexID]*forcing_accum + a_provenance[ProvenanceID] + a_clone[CloneID] + a_site[SiteID] + a_tree[TreeID_new],
        #priors
        beta[SexID] ~ dbeta(.5,5),
        cutpoints ~ dnorm(7.5, 3),
        a_clone[CloneID] ~ dnorm(0, sigma_clone),
        a_provenance[ProvenanceID] ~ dnorm(0, sigma_provenance),
        a_site[SiteID] ~ dnorm(0, sigma_site),
        a_tree[TreeID_new] ~ dnorm(0, sigma_tree),
        #hyperpriors
        sigma_clone ~ exponential(1.5),
        sigma_provenance ~ exponential(1.5),
        sigma_site ~ exponential(1.5),
        sigma_tree ~ exponential(1.5)
    ),
    data = phendf,
    warmup = 15, iter=25, chains = 1, cores = 1)

# write stancode generated by ulam (don't forget to edit!) ####
write(stancode(ulam_fit), file="2019-03-24_ulam_fit.stan")

# extract data from ulam fit and write it out for use in stan ####
data <- ulam_fit@data

Year <- data$Year
Index <- data$Index
Orchard <- data$Orchard
Phenophase_Derived <- data$Phenophase_Derived
forcing_accum <- data$forcing_accum
CloneID <- data$CloneID
OrchardID <- data$OrchardID
ProvenanceID <- data$ProvenanceID
SiteID <- data$SiteID
SexID <- data$SexID
TreeID_new <- data$TreeID_new


stan_rdump(names(data), file="2019-03-24_data_rdump.R")

# read in data and run stan model ####

input_data <- read_rdump('2019-03-24_data_rdump.R')

fit <- stan(file = '2019-03-24_ulam_fit.stan', data=input_data, chains = 6, iter=5000, algorithm = "NUTS", cores=6)


util$check_all_diagnostics(fit)

#save fit
saveRDS(fit, file = "~/Documents/research_phd/2019-03-24_mSsItcsp.rds")

# visualizations
posterior <- rstan::extract(fit)
posterior_array <- as.array(fit)
mcmc_areas_ridges(posterior_array, regex_pars="a_clone")
