---
title: "female strobili model examination"
author: "Susannah Tysor"
date: "April 17, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r depends}
library(rstan)
library(bayesplot)
library(ggplot2)
library(rethinking)
```

```{r model data}

fitfem.stan <- readRDS("2019-04-17_fem_intercept_only.rds")
femsum <- precis(fitfem.stan, depth = 2)
param_names <- fitfem.stan@model_pars
post <- as.array(fitfem.stan)
postsamples <- extract.samples(fitfem.stan)

```

```{calculate thresholds}
```

```{r check diagnostics}

lp <- log_posterior(fitfem.stan) #logposterior
np <- nuts_params(fitfem.stan) #nuts parameters

#divergent transitions

color_scheme_set("darkgray")

mcmc_parcoord(post, np=np, regex_pars = param_names[1:10])

mcmc_pairs(post, np=np, regex_pars = c("beta", "kappa"))

mcmc_pairs(post, np=np, regex_pars = c("prov"))
mcmc_pairs(post, np=np, regex_pars = c("site"))

mcmc_pairs(post, np=np, pars = c("a_prov[1]", "a_prov[2]", "a_site[1]", "a_site[2]" ))

color_scheme_set("mix-brightblue-gray")
mcmc_trace(post, regex_pars="kappa")

color_scheme_set("red")
mcmc_nuts_divergence(np, lp)

#energy
mcmc_nuts_energy(np)

#rhat
color_scheme_set("brightblue")
rhats <- rhat(fitfem.stan)
mcmc_rhat(rhats)
mcmc_rhat_hist(rhats)

#effective sample size
#ratios <- neff_ratio(postsamples)
#mcmc_neff(ratios, regex_pars="sigma")

#autocorrelation
mcmc_acf(post, regex_pars = "kappa", lags=10)
# lots of autocorrelation :( :())
mcmc_acf(post, regex_pars = "sigma")
```

```{r plot draws}
mcmc_intervals(post, regex_pars = c("sigma")) + ggtitle("sigmas")
mcmc_areas(post, regex_pars="sigma") + ggtitle("sigmas")
mcmc_intervals(post, regex_pars = c("a_prov", "a_site", "a_year")) + ggtitle("intercepts")
mcmc_intervals(post, regex_pars = c("a_clone")) + ggtitle("clone intercepts")
mcmc_areas(post, regex_pars = "kappa") + ggtitle("cutpoints")
mcmc_areas(post, pars="beta") + ggtitle("transition speed") 

```
